#server:
#  port: 9100
#spring:
#  application:
#    name: account
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: 95fc64fb-aea7-48d3-a890-d17860d5b132
#        group: dev
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 95fc64fb-aea7-48d3-a890-d17860d5b132
#        group: dev
#        file-extension: yaml